ALTER TABLE categories 
    ALTER COLUMN name TYPE VARCHAR(100),
    ALTER COLUMN name SET NOT NULL,
    ALTER COLUMN description TYPE VARCHAR(255);

ALTER TABLE products
    ALTER COLUMN name TYPE VARCHAR(100),
    ALTER COLUMN description TYPE VARCHAR(255),
    ALTER COLUMN price SET NOT NULL,
    ALTER COLUMN price TYPE DECIMAL(19,2),
    ALTER COLUMN status SET NOT NULL,
    ALTER COLUMN category_id SET NOT NULL;
